#!/usr/bin/env bash
# display all processes (a): user-oriented (u), w/wo TTY (x), show heirachy (f)
# Must show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

ps auxf
